### ISSUE TITLE
Lucas

### ISSUE THREAD

**Issue by adrian621** [adty3240/Drawline#61]
e kickad

**Comment by jakobemilandersson** [comment]
Jag tycker att vi ska ha ett möte om Lucas psykiska tillstånd... Han tror att han är Drawlines CEO. Vi är några i ledningen som tycker att vi ska tvångsmedicinera honom men vi känner att vi behöver hela styrelsen bakom oss! Hur känner ni? /Anonym men orolig medarbetare.

**Comment by adrian621** [comment]
Anonyma styrelsemedlemmar har redan lagt dex i hans kaffe i ett halvår utan några märkbara resultat. Tror på kicka istället :)

**Comment by jakobemilandersson** [comment]
Hm, okej det var tråkigt att höra... Vår ledning är bakom ditt förslag, hur ska vi ge honom dem dåliga nyheterna?

**Comment by lucatonile** [comment]
![fssh7df](https://cloud.githubusercontent.com/assets/14081394/24248669/9cd3d29e-0fd0-11e7-82b1-4a3a3e44747c.png)

**Comment by jakobemilandersson** [comment]
Har ledning fått några nyheter om Lucas Kristiansson Herrars tillstånd? Det senaste jag personligen fick höra var att han hade flyttat till Portugal med sin hund och lever i ett kollektiv där man delar sina fruar med varandra. /Orolig anonym medarbetare

**Comment by adrian621** [comment]
Hmm, tror bara det var hans hund som kom iväg på det äventyret. Vad beträffar Lucas Kristiansson Herrera så bor han, så vitt ledningen vet, fortfarande i en liten tidningslåda på perrongen vi Bagarmossens tunnelbanestation, där han tillverkar konst av kaliberlock, och säljer dessa för att en dag få pengar till ett äkta nationskort. Ledningen lovar att undersöka saken vidare. 

//Drawline CEO
